### ISSUE TITLE
[Bug]: Array signal not recognized

### ISSUE THREAD

**Issue by boluo-O** [wavedrom/vcdrom#35]
here is sample from https://vc.drom.io/?github=Mohammad-Heydariii/Digital-Systems-Lab-Course/main/Lab_project4/modelsim_files/clkdiv2n_tb.vcd

the result is like that
![企业微信截图_b3bf61fd-d867-48cd-a03c-90ec529c5a33](https://user-images.githubusercontent.com/32573416/220077990-b07ad1e4-5ae4-4c64-9f17-1f7320f7222c.png)

Array signal r_nxt is not displayed correctly，there are three signal r_nxt[2],r_nxt[1],r_nxt[0] in clkdiv2n_tb.vcd file, but in the wave form only one r_nxt wave, It seems that the array signal is not recognized

**Comment by drom** [comment]
Yes, very interesting.
ModelSim decided to store `r_reg` register as 3-bit vector, and `r_nxt` wire as 3 independent signals.
Let me see how To fix it.

**Comment by drom** [comment]
Please try again with new version.

**Comment by boluo-O** [comment]
The new version works perfectly! Thanks, this is very helpful to me.
