### ISSUE TITLE
Can you provide an example code for how to run this project in local?

### ISSUE THREAD

**Issue by meiying0101** [wavedrom/vcdrom#38]
I want to run this project in my local server, but I don't know how to achieve it after '''npm install'''.
Can you give some help, please?
Thanks a lot!

**Comment by obliguedon** [comment]
simple way to build and run the app localy

assuming that you already have `node`, `npm` and `python` installed.

## download and build the app

```shell
git clone https://github.com/wavedrom/vcdrom.git
cd ./vcdrom
npm i
./build.sh
```

## launch

```shell
cd ./app
python3 -m http.server 9000
```

now in your browser go to http://localhost:9000/

> I'm far from an expert in nodejs, this is just the way I use this app, don't know if its good or bad, but it work

**Comment by meiying0101** [comment]
Thanks for the help!!
When I finish the step, I got this error below, any suggestions?
![image](https://github.com/wavedrom/vcdrom/assets/14372823/4f18168d-6511-4497-8515-bd3cea035c17)

**Comment by meiying0101** [comment]
It works!! Thank you very much!!

**Comment by drom** [comment]
or you can run server this way:
```
http-server app
```
